spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#logging:
#  pattern:
#    console: "%d- %msg%n"
##  path: /var/log/tomcat
#  file: /var/log/tomcat/sell.log
##  level: debug
#   level:
#       com.coderpwh.LoggerTest: debug
